path_classifiers:
    macro:
        - Conversion/DeepCopy.FCMacro
        - Conversion/DxfToSketchLayers.FCMacro
        - Drawing/DrawingTitleBlock.FCMacro
        - Drawing/UnrollRuledSurface.FCMacro
        - FCRotateViewAbsolute.FCMacro
        - FEM/ExportFem.FCMacro
        - FEM/FemAnimateModeShapes.FCMacro
        - Foto.FCMacro
        - ImportExport/BmpImport.FCMacro
        - Information/CenterOfMass.FCMacro
        - Information/MeasureCircle.FCMacro
        - Information/SimpleProperties.FCMacro
        - Information/Tree2Ascii.FCMacro
        - ObjectCreation/AirfoilImportAndScale.FCMacro
        - ObjectCreation/BoxCreator.FCMacro
        - ObjectCreation/Draft_Circle_3_Points.FCMacro
        - ObjectCreation/EllipseCenter2Points.FCMacro
        - ObjectCreation/HalfHull.FCMacro
        - ObjectCreation/HyperbolaCreater.FCMacro
        - ObjectCreation/Macro_FCCircularText.FCMacro
        - ObjectCreation/MakeCircle3Points.FCMacro
        - ObjectCreation/ParabolaCreater.FCMacro
        - ObjectCreation/ScrewMaker.FCMacro
        - ObjectCreation/TableWithTnutSlots.FCMacro
        - ObjectCreation/TimingGear.FCMacro
        - ParametricObjectCreation/GeodesicDome.FCMacro
        - ParametricObjectCreation/Rectellipse.FCMacro
        - PureGui/Camera.FCMacro
        - PureGui/SplitPropEditor.FCMacro
        - PureGui/ViewRotation.FCMacro
        - Sketcher/SketchUnmap.FCMacro
        - Sketcher/SketcherClipView.FCMacro
        - Sketcher/SketcherRemap.FCMacro
        - SolidSweep.FCMacro
        - TechDraw/LasercutterSVGExport.FCMacro
        - TechDraw/TechDrawSymbolsLibrary.FCMacro
        - TechDraw/TechDrawViewSet.FCMacro
        - Utility/HighlightCommon.FCMacro
        - Utility/HighlightDifference.FCMacro
        - Utility/MessageBox.FCMacro
        - Utility/PlacementAbsolufy.FCMacro
        - Utility/SelectVisible.FCMacro
        - Utility/StraightenObject.FCMacro
